# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    base_path: "bundles/fosckeditor"
    js_path: "bundles/fosckeditor/ckeditor.js"
    configs:
        basic_config:
            toolbar: full
            filebrowserBrowseRoute: file_manager
            filebrowserBrowseRouteParameters:
                conf: default
                module: ckeditor
            filebrowserImageBrowseRoute: file_manager
            filebrowserImageBrowseRouteParameters:
                conf: default
                module: ckeditor
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
