sonata_admin:
    title: 'Eusko Admin'
    title_logo: 'images/logo.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        default_admin_route: edit

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
