twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@SonataForm/Form/datepicker.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'bootstrap_5_layout.html.twig'
    globals:
        yousign_url: '%env(YOUSIGN_URL)%'

when@test:
    twig:
        strict_variables: true

